project:
  type: website
  output-dir: docs

website:
  site-url: https://rluttinen.github.io/RebeccaLuttinen.github.io/

format:
  html:
    theme: none
    minimal: true
    # This ensures Quarto doesn't inject its own CSS that breaks Cayman
    include-in-header: 
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.1.0/github-markdown.min.css">

resources:
  - images/
